meta:
  version: 0.0.1
  author: philtherobot
  engine: 4.0.2
units:
  # cx, cy = Choc V1 spacing, 18×17
  # physical DMK keycap size = 17.5×16.5
  # We want a familiar horizontal spacing.
  # So spread = 19 (standard).
  # We want tighter as possible vertically
  # because we have four rows.
  # So padding = 17

  # TODO: the following does not reflect the
  # choices above. Furthermore, the wing for 
  # the pinky should be made closer horizontally
  # has the pinky has a harder time extending out.

  padx: 1
  pady: 1
  sidx: cx / 2
  sidy: cy / 2
  padmcu: 3
  spread: 19
  padding: 17
points:
  key:
    spread: spread
    padding: padding
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]

      columns:
        ring:
          key:
            col_net: net_ring
        middle:
          key:
            col_net: net_middle
        index:
          key:
            col_net: net_index
        inner:
          key:
            col_net: net_inner
      rows:
        bottom:
          row_net: net_bottom
        home:
          row_net: net_home
        top:
          row_net: net_top
        nums:
          row_net: net_nums
    wing:
      anchor:
        shift: [-2spread, -0.4cy]
      columns:
        tip:
          rows:
            bottom.skip: true
        pinky:
      rows:
        bottom:
        home:
          key:
            skip: false
        top:
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [-0.3cx, -padding]
      columns:
        left:
        right:
        center:
          key:
            splay: -45
            origin: [-5, -17]
        inner:
      rows:
        home:
#  mirror: 100
outlines:
  # "keycaps" is the positions of the keycaps
  keycaps:
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  # "keys_footprint" is the key positions
  keys_footprint:
    - what: rectangle
      bound: true
      where: true
      size: [spread+1, padding+1]
  
  # "polygon" is a shape to extend the PCB in certain places
  polygon:
    - what: polygon
      points:
        - ref: matrix_inner_nums
          shift: [0, cy/2+0.5]
        - ref: matrix_inner_nums
          shift: [40, cy/2+0.5]
        - ref: matrix_inner_nums
          shift: [40, -80]
        - ref: thumb_right_home
          shift: [cx/2, -cy/2-0.5]

  # "board" is the outline of the PCB
  board:
    - what: outline
      name: keys_footprint
    - what: outline
      name: polygon
      operation: add
      fillet: 2
  board_and_keycaps:
    - name: board
    - operation: stack
      name: keycaps

pcbs:
  handlebar:
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: choc
        where: true
        params:
          from: "{{col_net}}"
          to: "{{colrow}}"
          keycaps: false
          reverse: true
          hotswap: false
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]          
      mcu:
        #what: promicro
        what: elite-c
        params:
          # D3: 
          # D2: 
          # GND0: 
          # GND1:
          # ----- rows 
          D1: net_nums
          D0: net_top
          D4: net_home
          C6: net_bottom
          # D7: 
          # E6: 
          # B4: 
          # B5: 
          # ----- columns
          B7: net_inner
          D5: net_index
          C7: net_middle
          F1: net_ring
          F0: net_pinky
          B6: net_outer
          # B2: 
          # B3: 
          # B1: 
          # F7: 
          # F6: 
          # F5: 
          # F4: 
          # VCC: 
          # RST: 
          # GND2: 
          # B0:
        where:
          ref: matrix_inner_nums
          shift: [0.5cx + 17.78/2 + padmcu, 0.5cy - 33.02/2 - 2]
          rotate: -90
