meta:
  version: 0.0.1
  author: philtherobot
  engine: 4.0.2
units:
  # cx, cy = Choc V1 spacing, 18×17
  # physical DMK keycap size = 17.5×16.5
  # We want a familiar horizontal spacing.
  # So spread = 19 (standard).
  # We want tighter as possible vertically
  # because we have four rows.
  # So padding = 17

  # TODO: the following does not reflect the
  # choices above. Furthermore, the wing for 
  # the pinky should be made closer horizontally
  # has the pinky has a harder time extending out.

  padx: 1
  pady: 1
  sidx: cx / 2
  sidy: cy / 2
  padmcu: 3
  spread: 19
  padding: 17
points:
  key:
    spread: spread
    padding: padding
  zones:
    matrix:
      columns:
        ring:
          key:
            from_net: B1
        middle:
          key:
            from_net: B2
        index:
          key:
            from_net: B3
        inner:
          key:
            from_net: B4
      rows:
        bottom:
          key:
            to_net: C1
        home:
          key:
            to_net: C2
        top:
          key:
            to_net: C3
        nums:
          key:
            to_net: C4
    wing:
      key:
        from_net: GND
        to_net: GND
      anchor:
        shift: [-2spread, -0.4cy]
      columns:
        tip:
          rows:
            bottom.skip: true
        pinky:
      rows:
        bottom:
        home:
          key:
            skip: false
        top:
    thumb:
      key:
        from_net: GND
        to_net: GND
      anchor:
        ref: matrix_index_bottom
        shift: [-0.3cx, -padding]
      columns:
        left:
        right:
        center:
          key:
            splay: -45
            origin: [-5, -17]
        inner:
      rows:
        home:
#  mirror: 100
outlines:
  # "keycaps" is the positions of the keycaps
  keycaps:
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  # "keys_footprint" is the key positions
  keys_footprint:
    - what: rectangle
      bound: true
      where: true
      size: [spread+1, padding+1]
  
  # "polygon" is a shape to extend the PCB in certain places
  polygon:
    - what: polygon
      points:
        - ref: matrix_inner_nums
          shift: [0, cy/2+0.5]
        - ref: matrix_inner_nums
          shift: [40, cy/2+0.5]
        - ref: matrix_inner_nums
          shift: [40, -80]
        - ref: thumb_right_home
          shift: [cx/2, -cy/2-0.5]

  # "board" is the outline of the PCB
  board:
    - what: outline
      name: keys_footprint
    - what: outline
      name: polygon
      operation: add
      fillet: 2
  board_and_keycaps:
    - name: board
    - operation: stack
      name: keycaps
pcbs:
  handlebar:
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: choc
        where: /^matrix_.*/
        params:
          from: "{{from_net}}"
          to: "{{to_net}}"
          keycaps: true
          reverse: true
          hotswap: false
      mcu:
        what: elite-c
        where:
          ref: matrix_inner_nums
          shift: [0.5cx + 17.78/2 + padmcu, 0.5cy - 33.02/2 - 2]
          rotate: -90
