meta:
  version: 0.0.1
  author: philtherobot
  engine: 4.0.2
units:
  # cx, cy = Choc V1 spacing, 18×17
  # physical DMK keycap size = 17.5×16.5
  # We want a familiar horizontal spacing.
  # So spread = 19 (standard = u).
  # We want tighter as possible vertically
  # because we have four rows.
  # So padding = 17 (cy)

  spread: u     # 19mm
  padding: cy   # 17mm
  kcapx: 17.5
  kcapy: 16.5

  # Shifts around points to stretch the "board" polygon
  bpadx: cx / 2 + 1.5 
  bpady: cy / 2 + 1.5

  mcuwidth: 17.78
  mcuheight: 33.02
  mcushiftx: 0.5cx + mcuwidth/2 + 8
  mcushifty: 0.5cy - mcuheight/2 - 3

  resetwidth: 5
  resetheight: 5
  resetshiftx: 40
  resetshifty: -45

  trrswidth: 5
  trrsheight: 12
  trrsshiftx: 38
  trrsshifty: -33
  trrsrotate: -83.4

  indicatorwidth: 5
  indicatorheight: 5
  indicatorshiftx: 20
  indicatorshifty: -45

points:
  key:
    spread: spread
    padding: padding

  zones:
    # The central 4×4 matrix
    center:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]

      columns:
        ring:
          key:
            col_net: net_ring
        middle:
          key:
            col_net: net_middle
        index:
          key:
            col_net: net_index
        inner:
          key:
            col_net: net_inner

      rows:
        bottom:
          row_net: net_bottom
        home:
          row_net: net_home
        top:
          row_net: net_top
        nums:
          row_net: net_nums

    # The keys at the outer edge
    wing:
      key:
        spread: cx  # Tighter spread for the pinky

      anchor:
        ref: center_ring_bottom
        shift: [-2cx, -0.4cy]

      columns:
        outer:
          rows:
            bottom.skip: true
          key:
            col_net: net_outer
        pinky:
          key:
            col_net: net_pinky

      rows:
        bottom:
          row_net: net_bottom
        home:
          row_net: net_home
        top:
          row_net: net_top

    # The lower keys for the thumb
    thumb:
      anchor:
        ref: center_index_bottom
        shift: [-0.3cx, -padding]
      columns:
        left:
           key:
             col_net: net_ring
        right:
          key:
            col_net: net_middle
        center:
          key:
            splay: -45
            origin: [3, -11]
            col_net: net_index
        inner:
          key:
            col_net: net_inner
      rows:
        thumb:
          row_net: net_thumb

outlines:
  # "keycaps" is the positions of the DMK keycaps
  keycaps:
    - what: rectangle
      where: true
      size: [kcapx, kcapy]

  raw:
    - what: rectangle
      where: true
      size: [cx+1, cy+1]

  board:
    - what: polygon
      fillet: 2
      points:
        - ref: wing_outer_home
          shift: [-bpadx, -bpady]
        - ref: wing_outer_top
          shift: [-bpadx, bpady]
        - ref: center_ring_nums
          shift: [-bpadx, bpady]
        - ref: center_inner_nums
          shift: [bpadx, bpady]
        - ref: center_inner_nums
          shift: [40, bpady]
        - ref: thumb_inner_thumb
          shift: [bpadx, bpady]
        - ref: thumb_inner_thumb
          shift: [bpadx, -bpady]
        - ref: wing_pinky_bottom
          shift: [-bpadx, -bpady]

  mcu:
    - what: rectangle
      size: [mcuwidth, mcuheight]
      adjust: 
        ref: center_inner_nums
        shift: [mcushiftx, mcushifty] 

  reset:
    - what: rectangle
      size: [resetwidth, resetheight]      
      adjust:
        ref: center_inner_nums
        shift: [resetshiftx, resetshifty]

  trrs:
    - what: rectangle
      size: [trrswidth, trrsheight]
      adjust: 
        ref: center_inner_nums
        shift: [trrsshiftx, trrsshifty]
        rotate: trrsrotate

  indicator1:
    - what: rectangle
      size: [indicatorwidth, indicatorheight]
      adjust:
        ref: center_inner_nums
        shift: [indicatorshiftx, indicatorshifty]

  indicator2:
    - what: rectangle
      size: [indicatorwidth, indicatorheight]
      adjust:
        ref: center_inner_nums
        shift: [indicatorshiftx + indicatorwidth, indicatorshifty]

  preview:
    - name: board
    - operation: stack
      name: keycaps
    - operation: stack
      name: mcu 
    - operation: stack
      name: reset
    - operation: stack
      name: trrs  
    - operation: stack
      name: indicator1
    - operation: stack
      name: indicator2

pcbs:
  handlebar:
    outlines:
      main:
        outline: board
    footprints:

      keys:
        what: choc
        where: true
        params:
          from: "{{col_net}}"
          to: "{{colrow}}"
          keycaps: true
          reverse: true
          hotswap: false

      diode:
        what: diode_smd
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]     

      reset:
        what: button     
        params:
          from: ""
          to: ""
        where:
          ref: center_inner_nums
          shift: [resetshiftx, resetshifty]

      trrs:
        what: trrs
        params:
          reverse: true
          A: ""
          B: ""
          C: ""
          D: ""
        where:
          ref: center_inner_nums
          shift: [trrsshiftx, trrsshifty]
          rotate: trrsrotate

      indicator1:
        what: rgb
        params:
          designator: "I"
          din: ""
          dout: ""
          VCC: ""
          GND: ""
        where:
          ref: center_inner_nums
          shift: [indicatorshiftx, indicatorshifty]

      indicator2:
        what: rgb
        params:
          designator: "I"
          din: ""
          dout: ""
          VCC: ""
          GND: ""
        where:
          ref: center_inner_nums
          shift: [indicatorshiftx + indicatorwidth, indicatorshifty]
      mcu:
        #what: promicro
        what: elite-c
        params:
          reversable: true
          instructions: false
          reversable_pins: 12
          # D3: 
          # D2: 
          # GND0: 
          # GND1:
          # ----- rows 
          D1: net_nums
          D0: net_top
          D4: net_home
          C6: net_bottom
          D7: net_thumb
          # E6: 
          # B4: 
          # B5: 
          # ----- columns
          B7: net_inner
          D5: net_index
          C7: net_middle
          F1: net_ring
          F0: net_pinky
          B6: net_outer
          # B2: 
          # B3: 
          # B1: 
          # F7: 
          # F6: 
          # F5: 
          # F4: 
          # VCC: 
          # RST: 
          # GND2: 
          # B0:
        where:
          ref: center_inner_nums
          shift: [mcushiftx, mcushifty]
