meta:
  version: 0.0.1
  author: philtherobot
  engine: 4.0.2
units:
  # cx, cy = Choc V1 spacing, 18×17
  # physical DMK keycap size = 17.5×16.5
  # We want a familiar horizontal spacing.
  # So spread = 19 (standard = u).
  # We want tighter as possible vertically
  # because we have four rows.
  # So padding = 17 (cy)

  spread: u     # 19mm
  padding: cy   # 17mm
  kcapx: 17.5
  kcapy: 16.5

  # Shifts around points to stretch the "board" polygon
  bpadx: cx / 2 + 1.5 
  bpady: cy / 2 + 1.5

  mcuwidth: 17.78
  mcuheight: 33.02
  mcushiftx: 0.5cx + mcuwidth/2 + 8
  mcushifty: 0.5cy - mcuheight/2 - 3

  resetwidth: 5
  resetheight: 5
  resetshiftx: 40
  resetshifty: -50

  trrswidth: 6
  trrsheight: 14
  trrsshiftx: 44
  trrsshifty: -34
  trrsrotate: -83.4

  indicatorwidth: 5
  indicatorheight: 5
  indicatorshiftx: 20
  indicatorshifty: -45

points:
  key:
    spread: spread
    padding: padding

  zones:
    # The central 4×4 matrix
    center:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]

      columns:
        ring:
          key:
            col_net: n_ring
        middle:
          key:
            col_net: n_middle
        index:
          key:
            col_net: n_index
        inner:
          key:
            col_net: n_inner

      rows:
        bottom:
          row_net: n_bottom
        home:
          row_net: n_home
        top:
          row_net: n_top
        nums:
          row_net: n_nums

    # The keys at the outer edge
    wing:
      key:
        spread: cx  # Tighter spread for the pinky
        col_net: n_pinky # All those keys are in a single net column

      anchor:
        ref: center_ring_bottom
        shift: [-2cx, -0.4cy]

      columns:
        outer:
          rows:
            bottom.skip: true
            home.row_net: n_thumb
            top.row_net: n_nums
        pinky:

      rows:
        bottom:
          row_net: n_bottom
        home:
          row_net: n_home
        top:
          row_net: n_top

    # The lower keys for the thumb
    thumb:
      anchor:
        ref: center_index_bottom
        shift: [-0.3cx, -padding]
      columns:
        left:
           key:
             col_net: n_ring
        right:
          key:
            col_net: n_middle
        center:
          key:
            splay: -45
            origin: [3, -11]
            col_net: n_index
        inner:
          key:
            col_net: n_inner
      rows:
        thumb:
          row_net: n_thumb

outlines:
  # "keycaps" is the positions of the DMK keycaps
  keycaps:
    - what: rectangle
      where: true
      size: [kcapx, kcapy]

  raw:
    - what: rectangle
      where: true
      size: [cx+1, cy+1]

  board:
    - what: polygon
      fillet: 2
      points:
        - ref: wing_outer_home
          shift: [-bpadx, -bpady]
        - ref: wing_outer_top
          shift: [-bpadx, bpady]
        - ref: center_ring_nums
          shift: [-bpadx, bpady]
        - ref: center_inner_nums
          shift: [bpadx, bpady]
        - ref: center_inner_nums
          shift: [40, bpady]
        - ref: thumb_inner_thumb
          shift: [bpadx, bpady]
        - ref: thumb_inner_thumb
          shift: [bpadx, -bpady]
        - ref: wing_pinky_bottom
          shift: [-bpadx, -bpady]

  mcu:
    - what: rectangle
      size: [mcuwidth, mcuheight]
      adjust: 
        ref: center_inner_nums
        shift: [mcushiftx, mcushifty] 

  reset:
    - what: rectangle
      size: [resetwidth, resetheight]      
      adjust:
        ref: center_inner_nums
        shift: [resetshiftx, resetshifty]

  trrs:
    - what: rectangle
      size: [trrswidth, trrsheight]
      adjust: 
        ref: center_inner_nums
        shift: [trrsshiftx - 5, trrsshifty - 1]
        rotate: trrsrotate

  indicator1:
    - what: rectangle
      size: [indicatorwidth, indicatorheight]
      adjust:
        ref: center_inner_nums
        shift: [indicatorshiftx, indicatorshifty]

  indicator2:
    - what: rectangle
      size: [indicatorwidth, indicatorheight]
      adjust:
        ref: center_inner_nums
        shift: [indicatorshiftx + indicatorwidth, indicatorshifty]

  preview:
    - name: board
    - operation: stack
      name: keycaps
    - operation: stack
      name: mcu 
    - operation: stack
      name: reset
    - operation: stack
      name: trrs  
    - operation: stack
      name: indicator1
    - operation: stack
      name: indicator2

pcbs:
  handlebar:

    outlines:
      main:
        outline: board

    footprints:
      keys:
        what: choc
        where: true
        params:
          from: "{{colrow}}"
          to: "{{col_net}}"
          keycaps: true
          reverse: true
          hotswap: false

      diode:
        what: diode_smd
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]     

      keyvia1:
        what: via
        where: true
        params:
          net: "{{row_net}}"
        adjust:
          shift: [-2.15, -5]

      keyvia2:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [2.15, -5]

      reset:
        what: button     
        params:
          designator: rst
          from: n_reset
          to: n_gnd
        where:
          ref: center_inner_nums
          shift: [resetshiftx, resetshifty]

      trrs:
        what: trrs
        params:
          reverse: true
          A: n_gnd # sleeve
          B: n_sda # ring
          C: n_scl # ring
          D: n_vcc # tip
        where:
          ref: center_inner_nums
          shift: [trrsshiftx, trrsshifty]
          rotate: trrsrotate

      indicator1:
        what: rgb
        params:
          designator: "I"
          din: n_indic
          dout: n_indic_next
          VCC: n_vcc
          GND: n_gnd
        where:
          ref: center_inner_nums
          shift: [indicatorshiftx, indicatorshifty]
          rotate: 90

      indicator2:
        what: rgb
        params:
          designator: "I"
          din: n_indic_next
          dout: ""
          VCC: n_vcc
          GND: n_gnd
        where:
          ref: center_inner_nums
          shift: [indicatorshiftx + indicatorwidth, indicatorshifty]
          rotate: 90

      mcu:
        #what: promicro
        what: elite-c
        params:
          reversable: true
          instructions: false
          reversable_pins: 12
          # ----- left side, top to bottom
          # D3: 
          # D2: 
          GND: n_gnd
          # GND1: n_gnd
          D1: n_sda
          D0: n_scl
          D4: n_nums
          C6: n_top
          D7: n_home
          E6: n_bottom
          B4: n_indic
          # ----- seven bottom holes, cannot be reversed, so we do not use them
          # B5:
          # B7: 
          # D5: 
          # C7: 
          # F1: 
          # F0: 
          # B6:
          # ----- right side, bottom to top
          B2: n_thumb
          B3: n_inner
          B1: n_index
          F7: n_middle
          F6: n_ring
          F5: n_pinky
          # F4: 
          VCC: n_vcc
          RST: n_reset
          # GND2:
          # B0:
        where:
          ref: center_inner_nums
          shift: [mcushiftx, mcushifty]

      # Using mounting hole from this fork: https://github.com/MvEerd/ergogen/blob/mveerd/src/footprints/mountinghole.js
      mountinghole_top_left:
        what: mountinghole
        where:
          ref: center_inner_nums
          shift: [-81.6, -9]

      mountinghole_bottom_left:
        what: mountinghole
        where:
          ref: center_inner_nums
          shift: [-61, -64.6]

      mountinghole_top_right:
        what: mountinghole
        where:
          ref: center_inner_nums
          shift: [13, 0]

      mountinghole_bottom_right:
        what: mountinghole
        where:
          ref: center_inner_nums
          shift: [13.2, -78.6]
          